### ISSUE TITLE
Don't forget to execute the queries yourself!

### ISSUE THREAD

**Issue by Myke623** [xenforo-ltd/docs#21]
Rather than noting not to forget to run the SQL queries, how about including them for convenience? Here's what I used:

**Add column to table xf_forum**:
> ALTER TABLE \`xf_forum\` ADD \`demo_portal_auto_feature\` TINYINT NOT NULL DEFAULT '0';

**Add column to table xf_thread**:
> ALTER TABLE \`xf_thread\` ADD \`demo_portal_featured\` TINYINT NOT NULL DEFAULT '0';

**Create table xf_demo_portal_featured_thread with two columns (thread_id, featured_date)**:
> CREATE TABLE \`xf_demo_portal_featured_thread\` ( \`thread_id\` INT NOT NULL , \`featured_date\` INT NOT NULL , PRIMARY KEY (\`thread_id\`)) ENGINE = InnoDB;

**Comment by liamwli** [comment]
I think it’d make more sense to tell people to use the `setup-step` cli system.

**Comment by Myke623** [comment]
Oh, I completely forgot about that and that's probably what Chris originally meant by his note!

BTW, I think you mean `install-step` right?

**Comment by chrisdeeming** [comment]
Ironically, before we implemented the schema manager, the raw queries were just there, so generally "Don't forget to execute the queries yourself!" was supposed to be taken literally.

But it's a valid issue. We should mention the `install-step` command here (used to be called `setup-step`).

**Comment by liamwli** [comment]
Ah, yeah. I still have the old `setup-step` command (I'm guessing it's not included in new downloads, but obviously no files are deleted when upgrading so it stays).

**Comment by TommiGustafsson-HMP** [comment]
Instead of saying:
> Note
> Don't forget to execute the queries yourself!

as of 17 May 2018, it would best to advice learners to execute following commands using the CLI:

`php cmd.php xf-addon:install-step Demo/Portal 1`
`php cmd.php xf-addon:install-step Demo/Portal 2`
`php cmd.php xf-addon:install-step Demo/Portal 3`

They will also give good debug information, if the steps do not work.
